### ISSUE TITLE
Failing to find dependencies after installing with paclet

### ISSUE THREAD

**Issue by gorbet** [mfroeling/QMRITools#15] opened 2024-05-28 19:32 UTC
**Describe the bug**
QMRITools is unable to locate dependencies with GetAssetLocation for Elastix, Transformix, DcmToNii, and pigz.

**To Reproduce**
In Demonstrations.nb, running the "List of Resources" section results in:
Elastix   $Failed
Transformix   $Failed
DcmToNii   $Failed
pigz   $Failed

Directory paths to Demo, DemoData, GradientTool, and ColorData are all successfully found.

<img width="1119" alt="Screenshot 2024-05-28 at 14 55 13" src="https://github.com/mfroeling/QMRITools/assets/109981869/b1ce7339-ebe4-4a49-bb0d-747c240ccf89">

I am able to find the elastix, dcm2niix, and transformix applications in the paclet folder in Applications/MacOSX-x86-64/bin/

**System information:**
 - MacOS Ventura on MacBook Pro with Apple M1 Max chip
 - Mathematica version 14.0, Mac OS X ARM (64-bit) platform
 - QMRITools Version 3.17.0 installed with QMRITools-3.17.0.paclet

**Comment by 369358727** [comment] 2024-05-28 19:32
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by mfroeling** [comment] 2024-05-30 09:26
On my mac im not able to reproduce the error.
In the Pacletinfo.wl file the paths to the files are defined for the various OS versions. 
![image](https://github.com/mfroeling/QMRITools/assets/15890391/400037de-aab0-4a3e-9218-a6dcbb85a576)
pigz is not defined for mac so that should return $Failed

**Comment by gorbet** [comment] 2024-05-30 12:44
My Mac has an Apple Silicon chip.  $SystemID returns "MacOSX-ARM64".  

I have tried changing the /Library/Mathematica/Paclets/Repository/QMRITools-3.17.0/Applications/MacOSX-x86-64 folder name to MacOSX-ARM64 and I have also renamed this way in PacletInfo.wl but this does not seem to resolve the issue for elastix, transformix, and dcm2niix so I think I must still be missing something.

**Comment by mfroeling** [comment] 2024-05-30 15:23
Ah now I get the issue, I don't think you have to rename the folder, if a MacOSX-ARM64 can run MacOSX-x86-64 binaries. 

I think the PacletInfo.wl file you have to either add the appropriate $systemID for your mac or change the x86-64 to ARM64

So for example the elastix asset will then be

Only change the systemID
`{"Asset", "Root" -> "Applications/MacOSX-x86-64", "SystemID" -> "MacOSX-ARM64", "Assets" -> {{"Elastix", "bin/elastix"}}},`

Add both systemIDs both pointing to the same folder
{"Asset", "Root" -> "Applications/MacOSX-x86-64", "SystemID" -> "MacOSX-x86-64", "Assets" -> {{"Elastix", "bin/elastix"}}},
{"Asset", "Root" -> "Applications/MacOSX-x86-64", "SystemID" -> "MacOSX-ARM64", "Assets" -> {{"Elastix", "bin/elastix"}}},

If you need a different binary you have to add that folder and binary your self 
{"Asset", "Root" -> "Applications/MacOSX-x86-64", "SystemID" -> "MacOSX-x86-64", "Assets" -> {{"Elastix", "bin/elastix"}}},
{"Asset", "Root" -> "Applications/MacOSX-ARM64", "SystemID" -> "MacOSX-ARM64", "Assets" -> {{"Elastix", "bin/elastix"}}},

Hope this helps.

I will add the appropriate folders and binaries in the next release if you can confirm if the x86 binaries run on ARM

**Comment by gorbet** [comment] 2024-05-30 20:03
Thank you, your suggestions worked.  

I am able to use the function DcmToNii[] and the "Registration using Elastix" section of Demonstrations.nb works.  If there is anything else I should test to confirm that the MacOSx-x86-64 binaries work with ARM64, please let me know.

It might be useful for anyone else in the same situation to also know that I had to use PacletDirectoryLoad[] with the path to the QMRITools paclet repository to apply the paths that I changed in PacletInfo.wl.

**Comment by mfroeling** [comment] 2024-05-31 14:48
If the "Registration using Elastix" section of Demonstrations.nb works it should all be fine.
I will add the ARM cases to the next version.

PacletDirectoryLoad[] is only needed if you change the packet without restarting the kernel. 
When I develop I call my development toolbox which is nothing more than this:
```
PacletDirectoryLoad["workspace\\QMRITools\\QMRITools"];
PacletDataRebuild[]
Get["QMRITools`"]
```

Glad everything worked out. I'm closing the issue for now.

**Closed by mfroeling** 2024-05-31 14:48 UTC
